USE `center_domiciliation`;

-- Données de référence pour les formes juridiques
INSERT INTO ref_formes_juridiques (forme_juridique, template_folder) VALUES
('SARL AU', 'SARL AU'),
('SARL', 'SARL'),
('Personne Physique', ''),
('SA', 'SA'),
('Succurssale Etrangère', ''),
('Succurssale Marocaine', '');

-- Données de référence pour les tribunaux
INSERT INTO ref_tribunaux (tribunal, tribunal_type) VALUES
('Casablanca', 'Tribunal de commerce'),
('Rabat', 'Tribunal de commerce'),
('Marrakech', 'Tribunal de commerce'),
('Fes', 'Tribunal de commerce'),
('Agadir', 'Tribunal de commerce'),
('Tangier', 'Tribunal de commerce'),
('Meknes', 'Tribunal de commerce'),
('Tetouan', 'Tribunal de commerce'),
('Oujda', 'Tribunal de commerce'),
('Beni Mellal', 'Tribunal de commerce'),
('Khouribga', 'Tribunal de commerce'),
('Settat', 'Tribunal de commerce'),
('Casablanca', 'Tribunal de Première Instance'),
('Rabat', 'Tribunal de Première Instance'),
('Marrakech', 'Tribunal de Première Instance'),
('Fes', 'Tribunal de Première Instance'),
('Agadir', 'Tribunal de Première Instance'),
('Tangier', 'Tribunal de Première Instance'),
('Meknes', 'Tribunal de Première Instance'),
('Tetouan', 'Tribunal de Première Instance'),
('Oujda', 'Tribunal de Première Instance'),
('Beni Mellal', 'Tribunal de Première Instance'),
('Khouribga', 'Tribunal de Première Instance'),
('Oulad Teima', 'Tribunal de Première Instance'),
('Settat', 'Tribunal de Première Instance'),
('Khemisset', 'Tribunal de Première Instance'),
('Tiflet', 'Tribunal de Première Instance'),
('Skhirat-Temara', 'Tribunal de Première Instance'),
('Sidi Kacem', 'Tribunal de Première Instance'),
('Sidi Slimane', 'Tribunal de Première Instance'),
('Souk El Arbaa', 'Tribunal de Première Instance'),
('Taourirt', 'Tribunal de Première Instance');

-- Données de référence pour les adresses
INSERT INTO ref_ste_adresses (ste_adresse) VALUES
('123 Boulevard Hassan II'),
('45 Avenue Mohammed V'),
('12 Rue Dar El Baraka'),
('78 Avenue des FAR'),
('34 Rue Ghandouri'),
('56 Boulevard de la Corniche'),
('89 Place de la Concordance'),
('11 Rue Ibn Sina'),
('25 Avenue de Marrakech'),
('67 Boulevard de Paris'),
('43 Route de Meknes'),
('55 Boulevard Allal El Fassi'),
('88 Rue Ahmed Chaouki'),
('22 Avenue Hassan II (Downtown)'),
('99 Boulevard Moulay Ismail');

-- Données de référence pour les villes
INSERT INTO ref_villes (ville) VALUES
('Agadir'),
('Ait Melloul'),
('Al Hoceima'),
('Asilah'),
('Azemmour'),
('Azrou'),
('Beni Mellal'),
('Beni Ansar'),
('Berrechid'),
('Berkane'),
('Boujdour'),
('Boulemane'),
('Casablanca'),
('Chefchaouen'),
('Chichaoua'),
('Dakhla'),
('El Hajeb'),
('El Jadida'),
('El Kelaa Des Sraghna'),
('Errachidia'),
('Essaouira'),
('Fes'),
('Figuig'),
('Fnideq'),
('Guelmim'),
('Guercif'),
('Ifrane'),
('Inezgane'),
('Jerada'),
('Kelaat Mgouna'),
('Khemisset'),
('Khenifra'),
('Khouribga'),
('Ksar El Kebir'),
('Laayoune'),
('Larache'),
('Marrakech'),
('Martil'),
('Meknes'),
('Midelt'),
('Mohammedia'),
('Nador'),
('Ouarzazate'),
('Ouezzane'),
('Oujda'),
('Oulad Teima'),
('Rabat'),
('Safi'),
('Sale'),
('Sefrou'),
('Settat'),
('Sidi Bennour'),
('Sidi Ifni'),
('Sidi Kacem'),
('Sidi Slimane'),
('Skhirat'),
('Souk El Arbaa'),
('Tanger'),
('Tan-Tan'),
('Taourirt'),
('Taroudant'),
('Tata'),
('Taza'),
('Temara'),
('Tetouan'),
('Tiflet'),
('Tinghir'),
('Tiznit'),
('Youssoufia'),
('Zagora');

-- Données de référence pour les nationalités
INSERT INTO ref_nationalites (nationalite) VALUES
('Marocaine'),
('Française'),
('Belge'),
('Suisse'),
('Allemande'),
('Italienne'),
('Espagnole'),
('Portugaise'),
('Britannique'),
('Américaine'),
('Canadienne'),
('Algérienne'),
('Tunisienne'),
('Sénégalaise'),
('Camerounaise'),
('Gabonaise'),
('Ivoirienne'),
('Congolaise'),
('Guinéenne'),
('Malienne');

-- Données de référence pour les lieux de naissance
INSERT INTO ref_lieux_naissance (lieu_naissance) VALUES
('Casablanca'),
('Rabat'),
('Marrakech'),
('Fes'),
('Agadir'),
('Tangier'),
('Meknes'),
('Tetouan'),
('Oujda'),
('Beni Mellal'),
('Khouribga'),
('Essaouira'),
('Safi'),
('Azemmour'),
('Ouezzane'),
('Sefrou'),
('Taza'),
('Nador'),
('Hoceima'),
('Driouch');

-- Données de référence pour les qualités d'associé
INSERT INTO ref_qualites_associe (qualite_associe) VALUES
('Gérant'),
('Associé unique'),
('Associé majoritaire'),
('Associé minoritaire'),
('Président'),
('Directeur Général'),
('Actionnaire'),
('Porteur de parts');

-- Données de référence pour les activités
INSERT INTO ref_activites_statuts (activite) VALUES
('Commerce de gros'),
('Commerce de detail'),
('Restauration'),
('Hotel'),
('Transport'),
('Logistique'),
('Consulting'),
('Services IT'),
('Services de sante'),
('Education'),
('Immobilier'),
('Construction'),
('Manufacture'),
('Agriculture'),
('Peche'),
('Energie'),
('Telecommunications'),
('Banque et Finance'),
('Assurance'),
('Tourisme');

-- NMA 2010 : les 649 ACTIVITES (codes 4 chiffres) de la nomenclature marocaine des activites.
-- Sections (A-U), branches et sous-branches non stockees : la liste de choix ne contient que les activites.
-- Usage : dossiers de domiciliation uniquement (activite du certificat negatif).
-- Les ACTIVITES (Statuts) des dossiers Creation / Cession / PV AGO restent dans ref_activites_statuts.
INSERT INTO ref_activites_ompic (code, libelle, sort_order) VALUES
('0112', 'Culture du riz', 1),
('0113', 'Culture de légumes, de melons, de racines et de tubercules', 2),
('0114', 'Culture de la canne à sucre', 3),
('0115', 'Culture du tabac', 4),
('0116', 'Culture de plantes à fibres', 5),
('0117', 'Culture fourragères', 6),
('0119', 'Autres cultures non permanentes', 7),
('0121', 'Culture de la vigne', 8),
('0122', 'Culture des palmiers-dattiers', 9),
('0123', 'Culture d’autres fruits tropicaux et subtropicaux', 10),
('0124', 'Culture d’agrumes', 11),
('0125', 'Culture de fruits à pépins et à noyau', 12),
('0126', 'Culture d’autres fruits d’arbres ou d’arbustes et de fruits à coque', 13),
('0127', 'Culture de l’olivier', 14),
('0128', 'Culture d’autres fruits oléagineux', 15),
('0129', 'Autres cultures permanentes', 16),
('0130', 'Multiplication de plantes', 17),
('0141', 'Élevage de vaches laitières', 18),
('0142', 'Élevage d’autres bovins et de buffles', 19),
('0143', 'Élevage de chevaux et d’autres équidés', 20),
('0144', 'Élevage de chameaux et d’autres camélidés', 21),
('0145', 'Élevage d’ovins et de caprins', 22),
('0146', 'Élevage de volailles', 23),
('0149', 'Élevage d’autres animaux', 24),
('0150', 'Culture et élevage associés', 25),
('0161', 'Activités de soutien aux cultures', 26),
('0162', 'Activités de soutien à la production animale', 27),
('0163', 'Traitement primaire des récoltes', 28),
('0164', 'Traitement des semences', 29),
('0170', 'Chasse, piégeage et services annexes', 30),
('0210', 'Sylviculture et autres activités forestières', 31),
('0220', 'Exploitation forestière', 32),
('0231', 'Récolte du liège', 33),
('0232', 'Récolte de l’alfa', 34),
('0239', 'Récolte d’autres produits forestiers non ligneux poussant à l’état sauvage', 35),
('0240', 'Services de soutien à l’exploitation forestière', 36),
('0311', 'Pêche en mer', 37),
('0312', 'Pêche en eau douce', 38),
('0321', 'Aquaculture en mer', 39),
('0322', 'Aquaculture en eau douce', 40),
('0510', 'Extraction de houille', 41),
('0520', 'Extraction de lignite', 42),
('0610', 'Extraction de pétrole brut', 43),
('0620', 'Extraction de gaz naturel', 44),
('0710', 'Extraction de minerais de fer', 45),
('0720', 'Extraction de minerais de métaux non ferreux', 46),
('0811', 'Extraction de pierres ornementales et de construction, de calcaire industriel, de gypse, de craie et d’ardoise', 47),
('0812', 'Exploitation de gravières et sablières, extraction d’argiles et de kaolin', 48),
('0820', 'Extraction de phosphates naturels', 49),
('0891', 'Extraction des minéraux chimiques et d’engrais minéraux (hors phosphates naturels)', 50),
('0892', 'Extraction de tourbe', 51),
('0893', 'Production de sel', 52),
('0899', 'Autres activités extractives n.c.a.', 53),
('0910', 'Activités de soutien à l’extraction d’hydrocarbures', 54),
('0990', 'Activités de soutien aux autres industries extractives', 55),
('1011', 'Transformation et conservation de la viande de boucherie', 56),
('1012', 'Transformation et conservation de la viande de volaille', 57),
('1013', 'Préparation de produits à base de viande', 58),
('1021', 'Congélation et surgélation de poissons, de crustacés et de mollusques', 59),
('1022', 'Autres activités de transformation et de conservation de poissons, de crustacés et de mollusques', 60),
('1031', 'Transformation et conservation de tomates', 61),
('1032', 'Préparation de jus de fruits et légumes', 62),
('1039', 'Transformation et conservation d’autres fruits et légumes', 63),
('1041', 'Fabrication d’huiles d’olives', 64),
('1042', 'Fabrication d’huiles d’arganier', 65),
('1043', 'Fabrication d’autres huiles et graisses non comestibles', 66),
('1044', 'Fabrication de margarine et graisses comestibles similaires', 67),
('1051', 'Exploitation de laiteries et fabrication de fromage', 68),
('1052', 'Fabrication de glaces et sorbets', 69),
('1061', 'Travail des grains', 70),
('1062', 'Fabrication de produits amylacés', 71),
('1071', 'Fabrication de pain et de pâtisserie fraîche', 72),
('1072', 'Fabrication de biscuits, biscottes et pâtisseries de conservation', 73),
('1073', 'Fabrication de pâtes alimentaires et de couscous', 74),
('1081', 'Fabrication de sucre', 75),
('1082', 'Fabrication de cacao, chocolat et de produits de confiserie', 76),
('1083', 'Transformation du thé et du café', 77),
('1084', 'Fabrication de condiments et assaisonnements', 78),
('1085', 'Fabrication de plats préparés', 79),
('1086', 'Fabrication d’aliments homogénéisés et diététiques', 80),
('1089', 'Fabrication d’autres produits alimentaires n.c.a.', 81),
('1091', 'Fabrication d’aliments pour animaux de ferme', 82),
('1092', 'Fabrication d’aliments pour animaux de compagnie', 83),
('1101', 'Production de boissons alcooliques distillées', 84),
('1102', 'Production de boissons alcooliques non distillées', 85),
('1103', 'Fabrication de bière et de malt', 86),
('1104', 'Industrie des eaux minérales et autres eaux embouteillées', 87),
('1105', 'Industrie des boissons rafraîchissantes', 88),
('1200', 'Fabrication de produits à base de tabac', 89),
('1310', 'Préparation de fibres textiles et filature', 90),
('1320', 'Tissage', 91),
('1330', 'Ennoblissement textile', 92),
('1341', 'Fabrication manufacturière de tapis et moquettes', 93),
('1342', 'Fabrication manuelle de tapis', 94),
('1391', 'Fabrication d’étoffes à mailles', 95),
('1392', 'Fabrication d’articles textiles, sauf habillement', 96),
('1393', 'Fabrication artisanale d’articles textiles', 97),
('1394', 'Fabrication de ficelles, cordes et filets', 98),
('1395', 'Fabrication de non-tissés, sauf habillement', 99),
('1396', 'Fabrication d’autres textiles techniques et industriels', 100),
('1399', 'Fabrication d’autres textiles n.c.a.', 101),
('1411', 'Fabrication de vêtements en cuir', 102),
('1412', 'Fabrication de vêtements de travail', 103),
('1413', 'Fabrication de vêtements sur mesure', 104),
('1414', 'Fabrication industrielle de vêtements de dessus', 105),
('1415', 'Fabrication artisanale de vêtements traditionnels', 106),
('1416', 'Fabrication de vêtements de dessous', 107),
('1419', 'Fabrication d’autres vêtements et accessoires', 108),
('1420', 'Fabrication d’articles en fourrure', 109),
('1431', 'Fabrication d’articles chaussants à mailles', 110),
('1439', 'Fabrication d’autres articles à mailles', 111),
('1511', 'Apprêt et tannage des cuirs', 112),
('1512', 'Préparation et teinture des fourrures', 113),
('1513', 'Fabrication d’articles de voyage, de maroquinerie et de sellerie', 114),
('1514', 'Fabrication d’articles traditionnels de voyage, de maroquinerie et de sellerie', 115),
('1521', 'Fabrication manufacturière de chaussures', 116),
('1522', 'Fabrication manuelle de chaussures', 117),
('1610', 'Sciage et rabotage du bois', 118),
('1621', 'Fabrication de placage et de panneaux de bois', 119),
('1622', 'Fabrication de parquets assemblés', 120),
('1623', 'Fabrication de charpentes et d’autres menuiseries', 121),
('1624', 'Fabrication d’emballages en bois', 122),
('1625', 'Fabrication d’objets divers en bois', 123),
('1626', 'Fabrication d’objets en liège', 124),
('1629', 'Fabrication artisanale d’objets divers en bois; vannerie et sparterie', 125),
('1711', 'Fabrication de pâte à papier', 126),
('1712', 'Fabrication de papier et de carton', 127),
('1721', 'Fabrication de papier et carton ondulés et d’emballages en papier ou en carton', 128),
('1722', 'Fabrication d’articles en papier à usage sanitaire ou domestique', 129),
('1723', 'Fabrication d’articles de papeterie', 130),
('1724', 'Fabrication de papiers peints', 131),
('1729', 'Fabrication d’autres articles en papier ou en carton', 132),
('1811', 'Imprimerie de journaux', 133),
('1812', 'Autre imprimerie (labeur)', 134),
('1813', 'Activités de pré-presse', 135),
('1814', 'Reliure et activités connexes', 136),
('1820', 'Reproduction d’enregistrements', 137),
('1910', 'Cokéfaction', 138),
('1920', 'Raffinage du pétrole', 139),
('2011', 'Fabrication de gaz industriels', 140),
('2012', 'Fabrication de colorants et de pigments', 141),
('2013', 'Fabrication d’autres produits chimiques inorganiques de base', 142),
('2014', 'Fabrication d’autres produits chimiques organiques de base', 143),
('2015', 'Fabrication de produits azotés et d’engrais', 144),
('2016', 'Fabrication de matières plastiques de base', 145),
('2017', 'Fabrication de caoutchouc synthétique', 146),
('2020', 'Fabrication de pesticides et d’autres produits agrochimiques', 147),
('2030', 'Fabrication de peintures, vernis, encres et mastics', 148),
('2041', 'Fabrication de savons, détergents et produits d’entretien', 149),
('2042', 'Fabrication de parfums et de produits pour la toilette', 150),
('2051', 'Fabrication de produits explosifs', 151),
('2052', 'Fabrication de colles', 152),
('2053', 'Fabrication d’huiles essentielles', 153),
('2059', 'Fabrication d’autres produits chimiques n.c.a.', 154),
('2060', 'Fabrication de fibres artificielles ou synthétiques', 155),
('2110', 'Fabrication de produits pharmaceutiques de base', 156),
('2120', 'Fabrication de préparations pharmaceutiques', 157),
('2211', 'Fabrication et rechapage de pneumatiques', 158),
('2219', 'Fabrication d’autres articles en caoutchouc', 159),
('2221', 'Fabrication de plaques, feuilles, tubes et profilés en matières plastiques', 160),
('2222', 'Fabrication d’emballages en matières plastiques', 161),
('2223', 'Fabrication d’éléments en matières plastiques pour la construction', 162),
('2229', 'Fabrication d’autres articles en matières plastiques', 163),
('2311', 'Fabrication de verre plat', 164),
('2312', 'Façonnage et transformation du verre plat', 165),
('2313', 'Fabrication de verre creux', 166),
('2314', 'Fabrication de fibres de verre', 167),
('2319', 'Fabrication et façonnage d’autres articles en verre, y compris verre technique', 168),
('2320', 'Fabrication de produits réfractaires', 169),
('2331', 'Fabrication de carreaux en céramique', 170),
('2332', 'Fabrication de briques, tuiles et produits de construction en terre cuite', 171),
('2333', 'Fabrication de produits artisanaux à partir d’argile', 172),
('2341', 'Fabrication d’articles céramiques à usage domestique ou ornemental', 173),
('2342', 'Fabrication artisanale d’articles céramiques à usage domestique ou ornemental', 174),
('2343', 'Fabrication d’appareils sanitaires en céramique', 175),
('2344', 'Fabrication d’isolateurs et pièces isolantes en céramique', 176),
('2345', 'Fabrication d’autres produits céramiques à usage technique', 177),
('2349', 'Fabrication d’autres produits céramiques', 178),
('2351', 'Fabrication de ciment', 179),
('2352', 'Fabrication de chaux', 180),
('2353', 'Fabrication de plâtre', 181),
('2361', 'Fabrication d’éléments en béton pour la construction', 182),
('2362', 'Fabrication d’éléments en plâtre pour la construction', 183),
('2363', 'Fabrication de béton prêt à l’emploi', 184),
('2364', 'Fabrication de mortiers et bétons secs', 185),
('2365', 'Fabrication d’ouvrages en fibre-ciment', 186),
('2369', 'Fabrication d’autres ouvrages en béton, en ciment ou en plâtre', 187),
('2370', 'Taille, façonnage et finissage de pierres', 188),
('2391', 'Fabrication de produits abrasifs', 189),
('2399', 'Fabrication d’autres produits minéraux non métalliques n.c.a.', 190),
('2410', 'Sidérurgie', 191),
('2420', 'Fabrication de tubes, tuyaux, profilés creux et accessoires correspondants en acier', 192),
('2431', 'Étirage à froid de barres', 193),
('2432', 'Laminage à froid de feuillards', 194),
('2433', 'Profilage à froid par formage ou pliage', 195),
('2434', 'Tréfilage à froid', 196),
('2441', 'Production de métaux précieux', 197),
('2442', 'Métallurgie de l’aluminium', 198),
('2443', 'Métallurgie du plomb, du zinc ou de l’étain', 199),
('2444', 'Métallurgie du cuivre', 200),
('2445', 'Métallurgie des autres métaux non ferreux', 201),
('2446', 'Élaboration et transformation de matières nucléaires', 202),
('2451', 'Fonderie de fonte', 203),
('2452', 'Fonderie d’acier', 204),
('2453', 'Fonderie de métaux légers', 205),
('2454', 'Fonderie d’autres métaux non ferreux', 206),
('2511', 'Fabrication de structures métalliques et de parties de structures', 207),
('2512', 'Fabrication de portes et fenêtres en métal', 208),
('2521', 'Fabrication de radiateurs et de chaudières pour le chauffage central', 209),
('2522', 'Fabrication de récipients métalliques pour gaz comprimés ou liquéfiés', 210),
('2529', 'Fabrication d’autres réservoirs, citernes et conteneurs métalliques', 211),
('2530', 'Fabrication de générateurs de vapeur, à l’exception des chaudières pour le chauffage central', 212),
('2540', 'Fabrication d’armes et de munitions', 213),
('2550', 'Forge, emboutissage, estampage; métallurgie des poudres', 214),
('2561', 'Traitement et revêtement des métaux', 215),
('2562', 'Usinage', 216),
('2571', 'Fabrication de coutellerie', 217),
('2572', 'Fabrication de serrures et de ferrures', 218),
('2573', 'Fabrication d’outillage', 219),
('2591', 'Fabrication de fûts et emballages métalliques similaires', 220),
('2592', 'Fabrication d’emballages métalliques légers', 221),
('2593', 'Fabrication d’articles en fils métalliques, de chaînes et de ressorts', 222),
('2594', 'Fabrication de vis et de boulons', 223),
('2595', 'Fabrication artisanale d’ouvrages traditionnels en métaux', 224),
('2599', 'Fabrication d’autres produits métalliques n.c.a.', 225),
('2611', 'Fabrication de composants électroniques', 226),
('2612', 'Fabrication de cartes électroniques assemblées', 227),
('2620', 'Fabrication d’ordinateurs et d’équipements périphériques', 228),
('2630', 'Fabrication d’équipements de communication', 229),
('2640', 'Fabrication de produits électroniques grand public', 230),
('2651', 'Fabrication d’instruments et d’appareils de mesure, d’essai et de navigation', 231),
('2652', 'Horlogerie', 232),
('2660', 'Fabrication d’équipements d’irradiation médicale, d’équipements électromédicaux et électrothérapeutiques', 233),
('2670', 'Fabrication de matériels optique et photographique', 234),
('2680', 'Fabrication de supports magnétiques et optiques', 235),
('2711', 'Fabrication de moteurs, génératrices et transformateurs électriques', 236),
('2712', 'Fabrication de matériel de distribution et de commande électrique', 237),
('2720', 'Fabrication de piles et d’accumulateurs électriques', 238),
('2731', 'Fabrication de câbles de fibres optiques', 239),
('2732', 'Fabrication d’autres fils et câbles électroniques ou électriques', 240),
('2733', 'Fabrication de matériel d’installation électrique', 241),
('2740', 'Fabrication d’appareils d’éclairage électrique', 242),
('2751', 'Fabrication d’appareils électroménagers', 243),
('2752', 'Fabrication d’appareils ménagers non électriques', 244),
('2790', 'Fabrication d’autres matériels électriques', 245),
('2811', 'Fabrication de moteurs et turbines, à l’exception des moteurs d’avions et de véhicules', 246),
('2812', 'Fabrication d’équipements hydrauliques et pneumatiques', 247),
('2813', 'Fabrication d’autres pompes et compresseurs', 248),
('2814', 'Fabrication d’autres articles de robinetterie', 249),
('2815', 'Fabrication d’engrenages et d’organes mécaniques de transmission', 250),
('2821', 'Fabrication de fours et brûleurs', 251),
('2822', 'Fabrication de matériel de levage et de manutention', 252),
('2823', 'Fabrication de machines et d’équipements de bureau (à l’exception des ordinateurs et équipements périphériques)', 253),
('2824', 'Fabrication d’outillage portatif à moteur incorporé', 254),
('2825', 'Fabrication d’équipements aérauliques et frigorifiques industriels', 255),
('2829', 'Fabrication de machines diverses d’usage général', 256),
('2830', 'Fabrication de machines agricoles et forestières', 257),
('2841', 'Fabrication de machines de formage des métaux', 258),
('2849', 'Fabrication d’autres machines-outils', 259),
('2891', 'Fabrication de machines pour la métallurgie', 260),
('2892', 'Fabrication de machines pour l’extraction ou la construction', 261),
('2893', 'Fabrication de machines pour l’industrie agro-alimentaire', 262),
('2894', 'Fabrication de machines pour les industries textiles', 263),
('2895', 'Fabrication de machines pour les industries du papier et du carton', 264),
('2896', 'Fabrication de machines pour le travail du caoutchouc ou des plastiques', 265),
('2899', 'Fabrication d’autres machines d’usage spécifique n.c.a.', 266),
('2910', 'Construction de véhicules automobiles', 267),
('2920', 'Fabrication de carrosseries et remorques', 268),
('2931', 'Fabrication d’équipements électriques et électroniques automobiles', 269),
('2932', 'Fabrication d’autres équipements automobiles', 270),
('3011', 'Construction de navires et de structures flottantes', 271),
('3012', 'Construction de bateaux de plaisance', 272),
('3020', 'Construction de locomotives et d’autre matériel ferroviaire roulant', 273),
('3030', 'Construction aéronautique et spatiale', 274),
('3040', 'Construction de véhicules militaires de combat', 275),
('3091', 'Fabrication de motocycles', 276),
('3092', 'Fabrication de bicyclettes et de véhicules pour invalides', 277),
('3099', 'Fabrication d’autres équipements de transport n.c.a.', 278),
('3101', 'Fabrication de meubles de bureau et de magasin', 279),
('3102', 'Fabrication de meubles de cuisine', 280),
('3103', 'Fabrication de matelas', 281),
('3104', 'Industries connexes de l’ameublement', 282),
('3109', 'Fabrication d’autres meubles', 283),
('3211', 'Frappe de monnaie', 284),
('3212', 'Fabrication d’articles de joaillerie et bijouterie', 285),
('3213', 'Fabrication d’articles de bijouterie fantaisie et articles similaires', 286),
('3220', 'Fabrication d’instruments de musique', 287),
('3230', 'Fabrication d’articles de sport', 288),
('3240', 'Fabrication de jeux et jouets', 289),
('3250', 'Fabrication d’instruments et de fournitures à usage médical et dentaire', 290),
('3291', 'Fabrication d’articles de brosserie', 291),
('3299', 'Autres activités manufacturières n.c.a.', 292),
('3311', 'Réparation d’ouvrages en métaux', 293),
('3312', 'Réparation de machines et équipements mécaniques', 294),
('3313', 'Réparation de matériels électroniques et optiques', 295),
('3314', 'Réparation d’équipements électriques', 296),
('3315', 'Réparation et maintenance navale', 297),
('3316', 'Réparation et maintenance d’aéronefs et d’engins spatiaux', 298),
('3317', 'Réparation et maintenance d’autres équipements de transport', 299),
('3319', 'Réparation d’autres équipements', 300),
('3320', 'Installation de machines et d’équipements industriels', 301),
('3511', 'Production et transport d’électricité', 302),
('3512', 'Distribution et commerce d’électricité', 303),
('3520', 'Production et distribution de combustibles gazeux', 304),
('3530', 'Production et distribution de vapeur et d’air conditionné', 305),
('3600', 'Captage, traitement et distribution d’eau', 306),
('3700', 'Collecte et traitement des eaux usées', 307),
('3811', 'Collecte des déchets non dangereux', 308),
('3812', 'Collecte des déchets dangereux', 309),
('3821', 'Traitement et élimination des déchets non dangereux', 310),
('3822', 'Traitement et élimination des déchets dangereux', 311),
('3831', 'Démantèlement d’épaves', 312),
('3832', 'Récupération de déchets triés', 313),
('3900', 'Dépollution et autres services de gestion des déchets', 314),
('4110', 'Promotion immobilière', 315),
('4120', 'Construction de bâtiments résidentiels et non résidentiels', 316),
('4211', 'Construction de routes et autoroutes', 317),
('4212', 'Construction de voies ferrées de surface et souterraines', 318),
('4213', 'Construction de ponts et tunnels', 319),
('4221', 'Construction de réseaux pour fluides', 320),
('4222', 'Construction de réseaux électriques et de télécommunications', 321),
('4291', 'Construction d’ouvrages maritimes et fluviaux', 322),
('4299', 'Construction d’autres ouvrages de génie civil n.c.a.', 323),
('4311', 'Travaux de démolition', 324),
('4312', 'Travaux de préparation des sites', 325),
('4313', 'Forages et sondages', 326),
('4321', 'Installation électrique', 327),
('4322', 'Travaux de plomberie et installation de chauffage et de conditionnement d’air', 328),
('4329', 'Autres travaux d’installation', 329),
('4331', 'Travaux de plâtrerie', 330),
('4332', 'Travaux de menuiserie', 331),
('4333', 'Travaux de revêtement des sols et des murs', 332),
('4334', 'Miroiterie de bâtiment, vitrerie', 333),
('4335', 'Travaux de peinture', 334),
('4339', 'Autres travaux de finition', 335),
('4391', 'Travaux de couverture', 336),
('4399', 'Autres travaux de construction spécialisés n.c.a.', 337),
('4511', 'Commerce de voitures et de véhicules automobiles légers', 338),
('4519', 'Commerce d’autres véhicules automobiles', 339),
('4520', 'Entretien et réparation de véhicules automobiles', 340),
('4531', 'Commerce de gros d’équipements automobiles', 341),
('4532', 'Commerce de détail d’équipements automobiles', 342),
('4541', 'Commerce de motocycles', 343),
('4542', 'Réparation de motocycles', 344),
('4611', 'Intermédiaires du commerce en matières premières agricoles, animaux vivants, matières premières textiles et produits semi-finis', 345),
('4612', 'Intermédiaires du commerce en combustibles, métaux, minéraux et produits chimiques', 346),
('4613', 'Intermédiaires du commerce en bois et matériaux de construction', 347),
('4614', 'Intermédiaires du commerce en machines, équipements industriels, navires et avions', 348),
('4615', 'Intermédiaires du commerce en meubles, articles de ménage et quincaillerie', 349),
('4616', 'Intermédiaires du commerce en textiles, habillement, fourrures, chaussures et articles en cuir', 350),
('4617', 'Intermédiaires du commerce en denrées, boissons et tabac', 351),
('4618', 'Intermédiaires spécialisés dans le commerce d’autres produits spécifiques', 352),
('4619', 'Intermédiaires du commerce en produits divers', 353),
('4621', 'Commerce de gros de céréales et aliments pour le bétail', 354),
('4622', 'Commerce de gros de tabac non manufacturé', 355),
('4623', 'Commerce de gros de fleurs et plantes', 356),
('4624', 'Commerce de gros d’animaux vivants', 357),
('4625', 'Commerce de gros de cuirs et peaux', 358),
('4631', 'Commerce de gros de fruits et légumes', 359),
('4632', 'Commerce de gros de viandes et de produits à base de viande', 360),
('4633', 'Commerce de gros de produits laitiers, œufs, huiles et matières grasses comestibles', 361),
('4634', 'Commerce de gros de boissons', 362),
('4635', 'Commerce de gros de produits à base de tabac', 363),
('4636', 'Commerce de gros de sucre, cacao, chocolat, confiserie, café, thé et épices', 364),
('4637', 'Commerce de gros de poissons, crustacés et mollusques', 365),
('4638', 'Commerce de gros d’autres produits alimentaires', 366),
('4639', 'Commerce de gros non spécialisé de denrées', 367),
('4641', 'Commerce de gros de textiles', 368),
('4642', 'Commerce de gros d’habillement et de chaussures', 369),
('4643', 'Commerce de gros d’appareils électroménagers', 370),
('4644', 'Commerce de gros de vaisselle, verrerie et produits d’entretien', 371),
('4645', 'Commerce de gros de parfumerie et de produits de beauté', 372),
('4646', 'Commerce de gros de produits pharmaceutiques', 373),
('4647', 'Commerce de gros de meubles, de tapis et d’appareils d’éclairage', 374),
('4648', 'Commerce de gros d’articles d’horlogerie et de bijouterie', 375),
('4649', 'Commerce de gros d’autres biens domestiques', 376),
('4651', 'Commerce de gros d’ordinateurs, d’équipements informatiques périphériques et de logiciels', 377),
('4652', 'Commerce de gros de composants et d’équipements électroniques et de télécommunication', 378),
('4661', 'Commerce de gros de matériel agricole', 379),
('4662', 'Commerce de gros de machines-outils', 380),
('4663', 'Commerce de gros de machines pour l’extraction, la construction et le génie civil', 381),
('4664', 'Commerce de gros de machines pour l’industrie textile et l’habillement', 382),
('4665', 'Commerce de gros de mobilier de bureau', 383),
('4666', 'Commerce de gros d’autres machines et équipements de bureau', 384),
('4669', 'Commerce de gros d’autres machines et équipements', 385),
('4671', 'Commerce de gros de combustibles et de produits annexes', 386),
('4672', 'Commerce de gros de minerais et métaux', 387),
('4673', 'Commerce de gros de bois et de produits dérivés', 388),
('4674', 'Commerce de gros de matériaux de construction et d’appareils sanitaires', 389),
('4675', 'Commerce de gros de quincaillerie et fournitures pour plomberie et chauffage', 390),
('4676', 'Commerce de gros de produits chimiques', 391),
('4677', 'Commerce de gros d’autres produits intermédiaires', 392),
('4678', 'Commerce de gros de déchets et débris', 393),
('4690', 'Commerce de gros non spécialisé', 394),
('4711', 'Commerce d’alimentation générale', 395),
('4712', 'Superettes', 396),
('4713', 'Supermachés', 397),
('4714', 'Hypermarchés', 398),
('4715', 'Autre commerce de détail en magasin non spécialisé à prédominance alimentaire', 399),
('4716', 'Autre commerce de détail en magasin en produits divers de l’artisanat', 400),
('4719', 'Autre commerce de détail en magasin non spécialisé sans prédominance alimentaire', 401),
('4721', 'Commerce de détail de fruits et légumes en magasin spécialisé', 402),
('4722', 'Commerce de détail de viandes et de produits à base de viande en magasin spécialisé', 403),
('4723', 'Commerce de détail de poissons, crustacés et mollusques en magasin spécialisé', 404),
('4724', 'Commerce de détail de pain, pâtisserie et confiserie en magasin spécialisé', 405),
('4725', 'Commerce de détail de boissons en magasin spécialisé', 406),
('4726', 'Commerce de détail de produits à base de tabac en magasin spécialisé', 407),
('4729', 'Autres commerces de détail alimentaires en magasin spécialisé', 408),
('4730', 'Commerce de détail de carburants en magasin spécialisé', 409),
('4741', 'Commerce de détail d’ordinateurs, d’unités périphériques et de logiciels en magasin spécialisé', 410),
('4742', 'Commerce de détail de matériels de télécommunication en magasin spécialisé', 411),
('4743', 'Commerce de détail de matériels audio/vidéo en magasin spécialisé', 412),
('4751', 'Commerce de détail de textiles en magasin spécialisé', 413),
('4752', 'Commerce de détail de quincaillerie, peintures et verres en magasin spécialisé', 414),
('4753', 'Commerce de détail de tapis, moquettes et revêtements de murs et de sols en magasin spécialisé', 415),
('4754', 'Commerce de détail d’appareils électroménagers en magasin spécialisé', 416),
('4759', 'Commerce de détail de meubles, appareils d’éclairage et autres articles de ménage en magasin spécialisé', 417),
('4761', 'Commerce de détail de livres en magasin spécialisé', 418),
('4762', 'Commerce de détail de journaux et papeterie en magasin spécialisé', 419),
('4763', 'Commerce de détail d’enregistrements musicaux et vidéo en magasin spécialisé', 420),
('4764', 'Commerce de détail d’articles de sport en magasin spécialisé', 421),
('4765', 'Commerce de détail d’articles de jeux et jouets en magasin spécialisé', 422),
('4771', 'Commerce de détail d’habillement en magasin spécialisé', 423),
('4772', 'Commerce de détail de chaussures et d’articles en cuir en magasin spécialisé', 424),
('4773', 'Commerce de détail de produits pharmaceutiques en magasin spécialisé', 425),
('4774', 'Commerce de détail d’articles médicaux et orthopédiques en magasin spécialisé', 426),
('4775', 'Commerce de détail de parfumerie et de produits de beauté en magasin spécialisé', 427),
('4776', 'Commerce de détail d’optique et de photographie', 428),
('4777', 'Commerce de détail d’articles d’horlogerie et de bijouterie en magasin spécialisé', 429),
('4778', 'Autre commerce de détail de biens neufs en magasin spécialisé', 430),
('4779', 'Commerce de détail de biens d’occasion en magasin', 431),
('4781', 'Commerce de détail alimentaire sur éventaires et marchés', 432),
('4782', 'Commerce de détail de textiles, d’habillement et de chaussures sur éventaires et marchés', 433),
('4789', 'Autres commerces de détail sur éventaires et marchés', 434),
('4791', 'Vente par correspondance', 435),
('4792', 'Vente par Internet', 436),
('4799', 'Autres commerces de détail hors magasin, éventaires ou marchés', 437),
('4910', 'Transport ferroviaire interurbain de voyageurs', 438),
('4920', 'Transports ferroviaires de fret', 439),
('4931', 'Transports urbains et suburbains de voyageurs', 440),
('4932', 'Transports de voyageurs par taxis', 441),
('4939', 'Autres transports terrestres de voyageurs n.c.a.', 442),
('4941', 'Transports routiers de fret', 443),
('4942', 'Services de déménagement', 444),
('4950', 'Transports par conduites', 445),
('5010', 'Transports maritimes et côtiers de passagers', 446),
('5020', 'Transports maritimes et côtiers de fret', 447),
('5030', 'Transports fluviaux de passagers', 448),
('5040', 'Transports fluviaux de fret', 449),
('5110', 'Transports aériens de passagers', 450),
('5121', 'Transports aériens de fret', 451),
('5122', 'Transports spatiaux', 452),
('5211', 'Entreposage et stockage frigorifique', 453),
('5212', 'Entreposage et stockage non frigorifique', 454),
('5221', 'Services auxiliaires des transports terrestres', 455),
('5222', 'Services auxiliaires des transports par eau', 456),
('5223', 'Services auxiliaires des transports aériens', 457),
('5224', 'Manutention', 458),
('5229', 'Autres services auxiliaires des transports', 459),
('5310', 'Activités de poste dans le cadre d’une obligation de service universel', 460),
('5320', 'Autres activités de poste et de courrier', 461),
('5510', 'Hôtels et hébergement similaire', 462),
('5520', 'Hébergement touristique et autre hébergement de courte durée', 463),
('5530', 'Terrains de camping et parcs pour caravanes ou véhicules de loisirs', 464),
('5590', 'Autres hébergements', 465),
('5610', 'Restaurants et services de restauration mobile', 466),
('5621', 'Services des traiteurs', 467),
('5629', 'Autres services de restauration', 468),
('5631', 'Cafés', 469),
('5632', 'Débits de boissons alcoolisées', 470),
('5811', 'Édition de livres', 471),
('5812', 'Édition de répertoires et de fichiers d’adresses', 472),
('5813', 'Édition de journaux', 473),
('5814', 'Édition de revues et périodiques', 474),
('5819', 'Autres activités d’édition', 475),
('5821', 'Édition de jeux électroniques', 476),
('5829', 'Édition d’autres logiciels', 477),
('5911', 'Production de films cinématographiques, de vidéo et de programmes de télévision', 478),
('5912', 'Post-production de films cinématographiques, de vidéo et de programmes de télévision', 479),
('5913', 'Distribution de films cinématographiques, de vidéo et de programmes de télévision', 480),
('5914', 'Projection de films cinématographiques', 481),
('5920', 'Enregistrement sonore et édition musicale', 482),
('6010', 'Édition et diffusion de programmes radio', 483),
('6020', 'Programmation de télévision et télédiffusion', 484),
('6110', 'Télécommunications filaires', 485),
('6120', 'Télécommunications sans fil', 486),
('6130', 'Télécommunications par satellite', 487),
('6190', 'Autres activités de télécommunication', 488),
('6201', 'Programmation informatique', 489),
('6202', 'Conseil informatique', 490),
('6203', 'Gestion d’installations informatiques', 491),
('6209', 'Autres activités informatiques', 492),
('6311', 'Traitement de données, hébergement et activités connexes', 493),
('6312', 'Portails Internet', 494),
('6391', 'Activités des agences de presse', 495),
('6399', 'Autres services d’information n.c.a.', 496),
('6411', 'Activités de banque centrale', 497),
('6419', 'Autres intermédiations monétaires', 498),
('6420', 'Activités des sociétés holding', 499),
('6430', 'Fonds de placement et entités financières similaires', 500),
('6491', 'Crédit-bail', 501),
('6492', 'Autre distribution de crédit', 502),
('6499', 'Autres activités des services financiers, hors assurance et caisses de retraite, n.c.a.', 503),
('6511', 'Assurance vie', 504),
('6512', 'Autres assurances', 505),
('6520', 'Réassurance', 506),
('6530', 'Caisses de retraite', 507),
('6611', 'Administration de marchés financiers', 508),
('6612', 'Courtage de valeurs mobilières et de marchandises', 509),
('6619', 'Autres activités auxiliaires de services financiers, hors assurance et caisses de retraite', 510),
('6621', 'Évaluation des risques et dommages', 511),
('6622', 'Activités des agents et courtiers d’assurances', 512),
('6629', 'Autres activités auxiliaires d’assurance et de caisses de retraite', 513),
('6630', 'Gestion de fonds', 514),
('6810', 'Activités des marchands de biens immobiliers', 515),
('6821', 'Location et exploitation de biens immobiliers résidentiels propres ou loués', 516),
('6822', 'Location et exploitation de terrains', 517),
('6829', 'Location et exploitation d’autres biens immobiliers propres ou loués', 518),
('6831', 'Agences immobilières', 519),
('6832', 'Administration de biens immobiliers', 520),
('6910', 'Activités juridiques', 521),
('6920', 'Activités comptables', 522),
('7010', 'Activités des sièges sociaux', 523),
('7021', 'Conseil en relations publiques et communication', 524),
('7022', 'Conseil pour les affaires et autres conseils de gestion', 525),
('7111', 'Activités d’architecture', 526),
('7112', 'Activités d’ingénierie', 527),
('7120', 'Activités de contrôle et analyses techniques', 528),
('7211', 'Recherche-développement en biotechnologie', 529),
('7219', 'Recherche-développement en autres sciences physiques et naturelles', 530),
('7220', 'Recherche-développement en sciences humaines et sociales', 531),
('7311', 'Activités des agences de publicité', 532),
('7312', 'Régie publicitaire de médias', 533),
('7320', 'Études de marché et sondages', 534),
('7410', 'Activités spécialisées de design', 535),
('7420', 'Activités photographiques', 536),
('7430', 'Traduction et interprétation', 537),
('7490', 'Autres activités spécialisées, scientifiques et techniques n.c.a.', 538),
('7500', 'Activités vétérinaires', 539),
('7711', 'Location et location-bail de voitures et de véhicules automobiles légers', 540),
('7712', 'Location et location-bail de camions', 541),
('7721', 'Location et location-bail d’articles de loisirs et de sport', 542),
('7722', 'Location de vidéocassettes et disques vidéo', 543),
('7729', 'Location et location-bail d’autres biens personnels et domestiques', 544),
('7731', 'Location et location-bail de machines et équipements agricoles', 545),
('7732', 'Location et location-bail de machines et équipements pour la construction', 546),
('7733', 'Location et location-bail de machines de bureau et de matériel informatique', 547),
('7734', 'Location et location-bail de matériels de transport par eau', 548),
('7735', 'Location et location-bail de matériels de transport aérien', 549),
('7739', 'Location et location-bail d’autres machines, équipements et biens matériels n.c.a.', 550),
('7740', 'Location-bail de propriété intellectuelle et de produits similaires, à l’exception des œuvres soumises à copyright', 551),
('7810', 'Activités des agences de placement de main-d’œuvre', 552),
('7820', 'Activités des agences de travail temporaire', 553),
('7830', 'Autre mise à disposition de ressources humaines', 554),
('7911', 'Activités des agences de voyage', 555),
('7912', 'Activités des voyagistes', 556),
('7990', 'Autres services de réservation et activités connexes', 557),
('8010', 'Activités de sécurité privée', 558),
('8020', 'Activités liées aux systèmes de sécurité', 559),
('8030', 'Activités d’enquête', 560),
('8110', 'Activités combinées de soutien lié aux bâtiments', 561),
('8121', 'Nettoyage courant des bâtiments', 562),
('8122', 'Autres activités de nettoyage des bâtiments et nettoyage industriel', 563),
('8129', 'Autres activités de nettoyage', 564),
('8130', 'Services d’aménagement paysager', 565),
('8211', 'Services administratifs combinés de bureau', 566),
('8219', 'Photocopie, préparation de documents et autres activités spécialisées de soutien de bureau', 567),
('8220', 'Activités de centres d’appels', 568),
('8230', 'Organisation de salons professionnels et congrès', 569),
('8291', 'Activités des agences de recouvrement de factures et des sociétés d’information financière sur la clientèle', 570),
('8292', 'Activités de conditionnement', 571),
('8299', 'Autres activités de soutien aux entreprises n.c.a.', 572),
('8411', 'Administration publique générale', 573),
('8412', 'Administration publique (tutelle) de la santé, de la formation, de la culture et des services sociaux, autre que sécurité sociale', 574),
('8413', 'Administration publique (tutelle) des activités économiques', 575),
('8421', 'Affaires étrangères', 576),
('8422', 'Défense', 577),
('8423', 'Justice', 578),
('8424', 'Activités d’ordre public et de sécurité', 579),
('8425', 'Protection civile', 580),
('8430', 'Sécurité sociale obligatoire', 581),
('8511', 'Enseignement coranique', 582),
('8512', 'Enseignement pré-primaire', 583),
('8520', 'Enseignement primaire', 584),
('8531', 'Enseignement secondaire collégial général', 585),
('8532', 'Enseignement secondaire qualifiant général', 586),
('8533', 'Enseignement secondaire qualifiant technique ou professionnel', 587),
('8541', 'Enseignement post-Bac non supérieur (CPGE et BTS)', 588),
('8542', 'Enseignement supérieur', 589),
('8551', 'Enseignement de disciplines sportives et d’activités de loisirs', 590),
('8552', 'Enseignement culturel', 591),
('8553', 'Enseignement de la conduite', 592),
('8559', 'Enseignements divers', 593),
('8560', 'Activités de soutien à l’enseignement', 594),
('8610', 'Activités hospitalières', 595),
('8621', 'Activité des médecins généralistes', 596),
('8622', 'Activité des médecins spécialistes', 597),
('8623', 'Pratique dentaire', 598),
('8691', 'Laboratoires d’analyses médicales', 599),
('8692', 'Ambulances', 600),
('8693', 'Centres de collecte et banques de sang et d’organes', 601),
('8694', 'Soins hors d’un cadre réglementé', 602),
('8699', 'Autres activités pour la santé humaine', 603),
('8710', 'Hébergement médicalisé', 604),
('8720', 'Hébergement social pour personnes handicapées mentales, malades mentales et toxicomanes', 605),
('8730', 'Hébergement social pour personnes âgées ou handicapées physiques', 606),
('8790', 'Autres activités d’hébergement social', 607),
('8810', 'Action sociale sans hébergement pour personnes âgées et pour personnes handicapées', 608),
('8891', 'Action sociale sans hébergement pour jeunes enfants', 609),
('8899', 'Autre action sociale sans hébergement n.c.a.', 610),
('9001', 'Arts du spectacle vivant', 611),
('9002', 'Activités de soutien au spectacle vivant', 612),
('9003', 'Création artistique', 613),
('9004', 'Gestion de salles de spectacles et de conservatoires de musique', 614),
('9101', 'Gestion des bibliothèques et des archives et de centres culturels', 615),
('9102', 'Gestion des musées', 616),
('9103', 'Gestion des sites et monuments historiques et des attractions touristiques similaires', 617),
('9104', 'Gestion des jardins botaniques et zoologiques et des réserves naturelles', 618),
('9200', 'Organisation de jeux de hasard et d’argent', 619),
('9311', 'Gestion d’installations sportives', 620),
('9312', 'Activités de clubs de sports', 621),
('9313', 'Activités des centres de culture physique', 622),
('9319', 'Autres activités liées au sport', 623),
('9321', 'Activités des parcs d’attractions et parcs à thèmes', 624),
('9329', 'Autres activités récréatives et de loisirs', 625),
('9411', 'Activités des organisations patronales et consulaires', 626),
('9412', 'Activités des organisations professionnelles', 627),
('9420', 'Activités des syndicats de salariés', 628),
('9491', 'Activités des organisations religieuses', 629),
('9492', 'Activités des organisations politiques', 630),
('9499', 'Activités des organisations associatives n.c.a.', 631),
('9511', 'Réparation d’ordinateurs et d’équipements périphériques', 632),
('9512', 'Réparation d’équipements de communication', 633),
('9521', 'Réparation de produits électroniques grand public', 634),
('9522', 'Réparation d’appareils électroménagers et d’équipements pour la maison et le jardin', 635),
('9523', 'Réparation de chaussures et d’articles en cuir', 636),
('9524', 'Réparation de meubles et d’équipements du foyer', 637),
('9525', 'Réparation d’articles d’horlogerie et de bijouterie', 638),
('9529', 'Réparation d’autres biens personnels et domestiques', 639),
('9601', 'Blanchisserie-teinturerie', 640),
('9602', 'Coiffure et soins de beauté', 641),
('9603', 'Services funéraires', 642),
('9604', 'Activités thermales et de thalassothérapie', 643),
('9605', 'Bains et autres soins corporels', 644),
('9609', 'Autres services personnels n.c.a.', 645),
('9700', 'Activités des ménages en tant qu’employeurs de personnel domestique', 646),
('9810', 'Activités indifférenciées des ménages en tant que producteurs de biens pour usage propre', 647),
('9820', 'Activités indifférenciées des ménages en tant que producteurs de services pour usage propre', 648),
('9900', 'Activités des organisations et organismes extraterritoriaux', 649);

INSERT INTO societes (
    societe_dossier_domiciliation_number, societe_raison_sociale, societe_forme_juridique, societe_ice, societe_date_ice, societe_rc, societe_if,
    societe_capital, societe_part_social, societe_valeur_nominale, societe_date_exp_cert_neg, societe_adresse, societe_adresse_siege, societe_ville, societe_tribunal, societe_email,
    societe_telephone, societe_type_generation, societe_procedure_creation, societe_mode_depot
) VALUES
(
    'DOM-2026-001', 'Atlas Domiciliation', 'SARL', '001122334455667', '2026-01-10',
    'RC12345', 'IF778899', 100000.00, 100, 1000.00, '2026-12-31',
    '123 Boulevard Hassan II', '123 Boulevard Hassan II', 'Casablanca', 'Casablanca',
    'contact@atlas.test', '+212600000001', 'Standard', 'Creation', 'Electronique'
),
(
    'DOM-2026-002', 'Maghreb Services', 'SARL AU', '998877665544332', '2026-03-15',
    'RC54321', 'IF665544', 50000.00, 100, 500.00, '2027-03-14',
    '45 Avenue Mohammed V', '45 Avenue Mohammed V', 'Rabat', 'Casablanca',
    'admin@maghreb.test', '+212600000002', 'Standard', 'Creation', 'Physique'
);

INSERT INTO associes (
    societe_id, associe_nom_complet, associe_cin, associe_date_naissance, associe_lieu_naissance, associe_nationalite, associe_adresse, associe_telephone, associe_email,
    associe_qualite, associe_parts, associe_est_gerant
) VALUES
(
    1, 'Youssef El Idrissi', 'BK123456', '1990-01-01', 'Casablanca', 'Marocaine', 'Casablanca',
    '+212600000101', 'youssef@atlas.test', 'Associé majoritaire', 60, 1
),
(
    1, 'Salma Bennani', 'BE654321', '1992-04-10', 'Casablanca', 'Marocaine', 'Casablanca',
    '+212600000102', 'salma@atlas.test', 'Associé minoritaire', 40, 0
),
(
    2, 'Imane Alaoui', 'CD987654', '1988-09-15', 'Rabat', 'Marocaine', 'Rabat',
    '+212600000103', 'imane@maghreb.test', 'Associé unique', 100, 1
);

INSERT INTO contrats (
    societe_id, contrat_type, contrat_date, contrat_duree_mois, contrat_type_domiciliation,
    contrat_type_domiciliation_autre, contrat_date_debut, contrat_date_fin,
    contrat_loyer_ttc, contrat_frais_intermediaire, contrat_caution, contrat_tva_pourcent, contrat_loyer_ht,
    contrat_total_ht, contrat_pack_montant_ttc, contrat_pack_loyer_ttc, contrat_type_renouvellement,
    contrat_renouv_tva_pourcent, contrat_renouv_loyer_ht, contrat_renouv_total_ht,
    contrat_renouv_loyer_ttc, contrat_renouv_annuel_ttc, contrat_statut, contrat_notes
) VALUES
(
    1, 'Domiciliation commerciale', '2026-01-01', 12, 'Personne Morale', NULL,
    '2026-01-01', '2026-12-31', 1200.00, 300.00, 1200.00, 20.00, 1000.00,
    12000.00, 1500.00, 1250.00, 'Annuel', 20.00, 1000.00, 12000.00, 1200.00, 14400.00, 'actif',
    'Contrat annuel standard'
),
(
    2, 'Pack lancement', '2026-03-01', 12, 'Personne Morale', NULL,
    '2026-03-01', '2027-02-28', 900.00, 250.00, 900.00, 20.00, 750.00,
    9000.00, 1000.00, 900.00, 'Annuel', 20.00, 750.00, 9000.00, 900.00, 10800.00, 'actif',
    'Pack simplifie'
);

INSERT INTO collaborateurs (
    den_ste, nom_complet, fonction, collaborateur_type, collaborateur_code, collaborateur_nom,
    collaborateur_ice, collaborateur_tp, collaborateur_rc, collaborateur_if, collaborateur_tel_fixe,
    collaborateur_tel_mobile, collaborateur_adresse, collaborateur_email, email, telephone, date_debut, statut, notes
) VALUES
(
    'Atlas Domiciliation', 'Nadia Chraibi', 'Gestion administrative', 'externe-pm', 'EXP',
    'Nadia Chraibi', 'ICE-COL-001', 'TP001', 'RC-C001', 'IF-C001', '0522000001', '+212600000010',
    'Casablanca', 'nadia@atlas.test', 'nadia@atlas.test', '+212600000010', '2026-01-05', 'actif',
    'Suivi dossiers clients'
),
(
    NULL, 'Karim Tazi', 'Support operationnel', 'externe-pp', 'CLTD',
    'Karim Tazi', 'ICE-COL-002', 'TP002', 'RC-C002', 'IF-C002', '0522000002', '+212600000011',
    'Casablanca', 'karim@center.test', 'karim@center.test', '+212600000011', '2026-02-01', 'actif',
    'Appui polyvalent'
);

INSERT IGNORE INTO ref_ste_adresses (ste_adresse) VALUES
('HAY MOULAY ABDELLAH RUE 300 N 152 ETG 2 AIN CHOCK, CASABLANCA'),
('46 BD ZERKTOUNI ETG 2 APPT 6 CASABLANCA'),
('56 BOULEVARD MOULAY YOUSSEF 3EME ETAGE APPT 14, CASABLANCA');

INSERT IGNORE INTO ref_tribunaux (tribunal, tribunal_type) VALUES
('Casablanca', 'Tribunal de commerce'),
('Berrechid', 'Tribunal de commerce'),
('Mohammedia', 'Tribunal de commerce'),
('Berrechid', 'Tribunal de Première Instance'),
('Mohammedia', 'Tribunal de Première Instance');

INSERT IGNORE INTO ref_activites_statuts (activite) VALUES
('Travaux Divers ou de Construction'),
('Marchand effectuant Import Export'),
('Négociant'),
('Conseil de Gestion');

INSERT IGNORE INTO ref_nationalites (nationalite) VALUES
('Marocaine'),
('Cameronnie');

INSERT IGNORE INTO ref_lieux_naissance (lieu_naissance) VALUES
('Casablanca'),
('Rabat'),
('Mohammedia');

-- Villes marocaines de reference (liste complete, idempotent via uq_ref_villes)
INSERT IGNORE INTO ref_villes (ville, sort_order) VALUES
('Agadir', 1000),
('Ait Melloul', 1010),
('Al Hoceima', 1020),
('Asilah', 1030),
('Azemmour', 1040),
('Azrou', 1050),
('Beni Ansar', 1060),
('Beni Mellal', 1070),
('Berkane', 1080),
('Berrechid', 1090),
('Bouarfa', 1100),
('Boujdour', 1110),
('Boulemane', 1120),
('Casablanca', 1130),
('Chefchaouen', 1140),
('Chichaoua', 1150),
('Dakhla', 1160),
('Demnate', 1170),
('Deroua', 1180),
('Driouch', 1190),
('El Hajeb', 1200),
('El Jadida', 1210),
('Errachidia', 1220),
('Es-Smara', 1230),
('Essaouira', 1240),
('Fes', 1250),
('Figuig', 1260),
('Fnideq', 1270),
('Goulmima', 1280),
('Guelmim', 1290),
('Guercif', 1300),
('Ifrane', 1310),
('Imzouren', 1320),
('Jerada', 1330),
('Kalaat M''Gouna', 1340),
('Kelaat Es-Sraghna', 1350),
('Kenitra', 1360),
('Khemisset', 1370),
('Khenifra', 1380),
('Khouribga', 1390),
('Laayoune', 1400),
('Larache', 1410),
('Marrakech', 1420),
('Martil', 1430),
('Meknes', 1440),
('Midelt', 1450),
('Mirleft', 1460),
('Mohammedia', 1470),
('Moulay Idriss Zerhoun', 1480),
('Nador', 1490),
('Ouarzazate', 1500),
('Oued Zem', 1510),
('Oujda', 1520),
('Rabat', 1530),
('Safi', 1540),
('Sale', 1550),
('Sefrou', 1560),
('Settat', 1570),
('Sidi Ifni', 1580),
('Sidi Kacem', 1590),
('Sidi Slimane', 1600),
('Skhirat', 1610),
('Tan-Tan', 1620),
('Tanger', 1630),
('Taza', 1640),
('Temara', 1650),
('Tiflet', 1660),
('Tinghir', 1670),
('Youssoufia', 1680),
('Zagora', 1690),
('Zaio', 1700);

INSERT IGNORE INTO ref_qualites_associe (qualite_associe) VALUES
('Gérant'),
('Associé unique');

-- RBAC Seed Data
INSERT IGNORE INTO roles (id, nom, description, is_internal, is_system, sort_order) VALUES
(1,  'Super Admin',       'Accès total au système',                         1, 1, 1),
(2,  'Admin',             'Administrateur avec presque tous les droits',    1, 0, 2),
(3,  'Chef d équipes',    'Gère les dossiers et son équipe',               1, 0, 3),
(4,  'Employé',           'Agent de traitement des dossiers',              1, 0, 4),
(5,  'Assistante',        'Support administratif et documentaire',          1, 0, 5),
(6,  'Stagiaire',         'Accès lecture seule',                           1, 0, 6),
(7,  'Expert-comptable',  'Expert-comptable externe',                      0, 0, 10),
(8,  'Comptable agréé',   'Comptable agréé externe',                       0, 0, 11),
(9,  'Commissaire aux comptes', 'Commissaire aux comptes',                 0, 0, 12),
(10, 'Coursier',          'Coursier / livreur',                             0, 0, 13),
(11, 'Avocat',            'Avocat externe',                                 0, 0, 14),
(12, 'Notaire',           'Notaire externe',                                0, 0, 15),
(13, 'Conseil juridique', 'Conseil juridique externe',                      0, 0, 16),
(14, 'Banque',            'Représentant bancaire',                          0, 0, 17),
(15, 'Assurance',         'Représentant assurance',                         0, 0, 18),
(16, 'Autre',             'Autre type de collaborateur',                    0, 0, 99);

INSERT IGNORE INTO permissions (id, nom, permission_key, category, description) VALUES
(1,  'Voir le tableau de bord',                       'dashboard.view',       'dashboard',    'Accéder au tableau de bord'),
(2,  'Voir les sociétés',                             'societes.view',        'societes',     'Consulter la liste et les fiches sociétés'),
(3,  'Créer une société',                             'societes.create',      'societes',     'Créer une nouvelle société'),
(4,  'Modifier une société',                          'societes.edit',        'societes',     'Modifier les informations d une société'),
(5,  'Supprimer une société',                         'societes.delete',      'societes',     'Supprimer une société'),
(6,  'Exporter les sociétés',                         'societes.export',      'societes',     'Exporter la liste des sociétés en CSV'),
(7,  'Voir les associés',                             'associes.view',        'associes',     'Consulter la liste des associés'),
(8,  'Créer un associé',                              'associes.create',      'associes',     'Ajouter un associé'),
(9,  'Modifier un associé',                           'associes.edit',        'associes',     'Modifier les informations d un associé'),
(10, 'Supprimer un associé',                          'associes.delete',      'associes',     'Supprimer un associé'),
(11, 'Exporter les associés',                         'associes.export',      'associes',     'Exporter la liste des associés en CSV'),
(12, 'Voir les contrats',                             'contrats.view',        'contrats',     'Consulter la liste des contrats'),
(13, 'Créer un contrat',                              'contrats.create',      'contrats',     'Ajouter un contrat'),
(14, 'Modifier un contrat',                           'contrats.edit',        'contrats',     'Modifier les informations d un contrat'),
(15, 'Supprimer un contrat',                          'contrats.delete',      'contrats',     'Supprimer un contrat'),
(16, 'Exporter les contrats',                         'contrats.export',      'contrats',     'Exporter la liste des contrats en CSV'),
(17, 'Voir les collaborateurs',                       'collaborateurs.view',       'collaborateurs', 'Consulter la liste des collaborateurs'),
(18, 'Créer un collaborateur',                        'collaborateurs.create',     'collaborateurs', 'Ajouter un collaborateur'),
(19, 'Modifier un collaborateur',                     'collaborateurs.edit',       'collaborateurs', 'Modifier les informations d un collaborateur'),
(20, 'Supprimer un collaborateur',                    'collaborateurs.delete',     'collaborateurs', 'Supprimer un collaborateur'),
(21, 'Exporter les collaborateurs',                   'collaborateurs.export',     'collaborateurs', 'Exporter la liste des collaborateurs en CSV'),
(22, 'Utiliser l assistant de création',              'wizard.create',        'wizard',       'Accéder au wizard de création de dossier'),
(23, 'Voir les templates',                            'templates.view',       'templates',    'Consulter la liste des templates'),
(24, 'Créer un template',                             'templates.create',     'templates',    'Ajouter un nouveau template'),
(25, 'Modifier un template',                          'templates.edit',       'templates',    'Modifier un template existant'),
(26, 'Supprimer un template',                         'templates.delete',     'templates',    'Supprimer un template'),
(27, 'Utiliser le générateur de dossiers',            'generation.use',       'generation',   'Générer les documents d un dossier'),
(28, 'Voir les documents générés',                    'documents.view',       'documents',    'Consulter la liste des documents'),
(29, 'Télécharger les documents',                     'documents.download',   'documents',    'Télécharger les fichiers générés'),
(30, 'Voir la configuration',                         'configuration.view',   'configuration','Accéder à la page de configuration'),
(31, 'Modifier la configuration',                     'configuration.edit',   'configuration','Modifier les données de configuration'),
(32, 'Voir l analyse de couverture',                  'analyse.view',         'analyse',      'Accéder à l analyse de couverture'),
(33, 'Voir les variables',                            'variables.view',       'variables',    'Consulter la gestion des variables'),
(34, 'Modifier les variables',                        'variables.edit',       'variables',    'Renommer et supprimer des variables'),
(35, 'Modifier les valeurs par défaut',               'defaults.edit',        'defaults',     'Configurer les valeurs par défaut'),
(36, 'Utiliser la conversion Word → PDF',             'convert.use',          'convert',      'Accéder à l outil de conversion'),
(37, 'Utiliser l assistant IA',                       'ai.use',               'ai',           'Accéder à l assistant IA'),
(38, 'Gérer les rôles et permissions',                'roles.manage',         'roles',        'Créer, modifier et supprimer des rôles');

-- Super Admin: ALL permissions
INSERT INTO role_permissions (role_id, permission_id)
SELECT 1, id FROM permissions;

-- Admin: all except roles.manage
INSERT INTO role_permissions (role_id, permission_id)
SELECT 2, id FROM permissions WHERE id < 38;

-- Super Admin collaborator (default password: admin123)
INSERT INTO collaborateurs (nom_complet, fonction, role_id, collaborateur_email, email, can_login, password_hash, statut, notes)
SELECT 'Super Admin', 'Administrateur système', 1, 'admin@center.test', 'admin@center.test', 1,
       '$2y$10$InXgIS0Eimx.ageF6OVGxu3J7pKvrtElbv2dnnWJsS0uBIfnQ6KTG', 'actif',
       'Compte super admin par defaut'
WHERE NOT EXISTS (SELECT 1 FROM collaborateurs WHERE email = 'admin@center.test' OR collaborateur_email = 'admin@center.test');
