CREATE TABLE IF NOT EXISTS pv_resolutions_templates (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    category VARCHAR(50) DEFAULT 'cession',
    sort_order INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

INSERT IGNORE INTO permissions (nom, permission_key, category, description) VALUES
('Voir les modèles de résolutions', 'pv_resolutions.view', 'configuration', 'Consulter les modèles de résolutions PV'),
('Créer un modèle de résolution', 'pv_resolutions.create', 'configuration', 'Créer un nouveau modèle'),
('Modifier un modèle de résolution', 'pv_resolutions.edit', 'configuration', 'Modifier un modèle existant'),
('Supprimer un modèle de résolution', 'pv_resolutions.delete', 'configuration', 'Supprimer un modèle');

INSERT IGNORE INTO pv_resolutions_templates (title, content, category, sort_order) VALUES
('Cession de parts sociales',
 'L\'Assemblée Générale, **« **[Cédant]** »** déclare céder à **« [Cessionnaire] »** **[NbParts]** parts sociales de **[ValeurNominale]** DH chacune, pour un montant total de **[PrixTotal]** DH.\n\nL\'Assemblée accepte expressément cette cession et reconnaît que le prix de cession a été réglé entre les parties.',
 'cession', 10),
('Agrément du cessionnaire',
 'L\'Assemblée Générale agrée la cession susmentionnée et accepte l\'entrée de **« [Cessionnaire] »** en qualité d\'associé au sein de la société.',
 'cession', 20),
('Modification des statuts — Capital',
 'En conséquence de la cession, l\'article relatif au capital social est modifié comme suit :\n\nLe capital social de **[Capital]** DH est divisé en **[NbPartsTotal]** parts de **[ValeurNominale]** DH chacune, réparties entre les associés.\n\nTous pouvoirs sont donnés au gérant pour accomplir les formalités de modification.',
 'cession', 30),
('Démission du gérant',
 'L\'Assemblée Générale prend acte de la démission de **« [AncienGérant] »** de ses fonctions de gérant de la société, avec effet à compter de ce jour, et le remercie pour les services rendus.',
 'cession', 40),
('Nomination du gérant',
 'L\'Assemblée Générale décide de nommer **« [NouveauGérant] »** en qualité de gérant de la société, pour une durée indéterminée, avec tous les pouvoirs nécessaires à l\'exercice de ses fonctions.',
 'cession', 50),
('Transformation SARL AU → SARL',
 'L\'Assemblée Générale décide de transformer la forme juridique de la société de SARL à Associé Unique (SARL AU) en SARL à associés multiples, conformément aux dispositions de la loi 5-96 modifiée.\n\nLes statuts seront modifiés en conséquence.',
 'cession', 60),
('Pouvoirs pour formalités',
 'Tous pouvoirs sont donnés à **« [Cédant] »** pour effectuer toutes formalités de dépôt et d\'inscription modificative auprès du greffe du tribunal de commerce, ainsi que toutes autres démarches requises par la loi.',
 'cession', 70),
('Changement d''objet social',
 'L\'Assemblée Générale décide de modifier l\'article relatif à l\'objet social, qui sera désormais rédigé comme suit :\n\n« La société a pour objet : **[détailler le nouvel objet]** »\n\nTous pouvoirs sont donnés au gérant pour accomplir les formalités de dépôt et d\'inscription modificative.',
 'general', 80),
('Transfert du siège social',
 'L\'Assemblée Générale décide de transférer le siège social de **[AncienneAdresse]** à **[NouvelleAdresse]**.\n\nL\'article relatif au siège social sera modifié en conséquence.\n\nTous pouvoirs sont donnés au gérant pour effectuer les formalités légales.',
 'general', 90),
('Changement de dénomination sociale',
 'L\'Assemblée Générale décide de modifier la dénomination sociale, qui sera désormais : **« [NouvelleDénomination] »**.\n\nL\'article relatif à la dénomination sera modifié en conséquence.\n\nTous pouvoirs sont donnés au gérant pour effectuer les formalités.',
 'general', 100),
('Augmentation du capital social',
 'L\'Assemblée Générale décide d\'augmenter le capital social d\'un montant de **[MontantAugmentation]** DH par création de **[NbPartsNouvelles]** parts sociales nouvelles de **[ValeurNominale]** DH chacune.\n\nLe capital social sera ainsi porté de **[CapitalAvant]** DH à **[CapitalAprès]** DH.\n\nL\'article relatif au capital social sera modifié en conséquence.',
 'general', 110),
('Modification de la durée de la société',
 'L\'Assemblée Générale décide de proroger la durée de la société de **[NbAnnées]** années, soit jusqu\'au **[NouvelleDateExpiration]**.\n\nL\'article relatif à la durée sera modifié en conséquence.\n\nTous pouvoirs sont donnés au gérant pour effectuer les formalités.',
 'general', 120),
('Clause d''agrément',
 'L\'Assemblée Générale décide d\'insérer une clause d\'agrément dans les statuts, soumettant toute cession de parts à un agrément préalable de la gérance.\n\nUn nouvel article sera inséré dans les statuts à cet effet.',
 'general', 130),
('Nomination d''un commissaire aux comptes',
 'L\'Assemblée Générale décide de nommer **[NomCAC]** en qualité de commissaire aux comptes titulaire, pour un mandat de six exercices, conformément aux dispositions légales en vigueur.',
 'general', 140),
('Révocation du gérant',
 'L\'Assemblée Générale décide de révoquer **« [AncienGérant] »** de ses fonctions de gérant, avec effet immédiat, et de nommer **« [NouveauGérant] »** en qualité de nouveau gérant pour une durée indéterminée.',
 'general', 150),
('Adoption de nouveaux statuts',
 'L\'Assemblée Générale décide d\'adopter les nouveaux statuts de la société, lesquels annulent et remplacent les précédents statuts.\n\nUne copie des nouveaux statuts sera annexée au présent procès-verbal.\n\nTous pouvoirs sont donnés au gérant pour effectuer les formalités de dépôt.',
 'general', 160);
